TARJETA PRIORITY PASS N° : 469771178134 | BORDA/L FERNANDO
FerBorda5


alias: Puls Hab 1 Single
description: ''
trigger:
  - platform: event
    event_type: state_changed
    event_data:
      entity_id: sensor.sonoff_a44000735c
condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: sensor.sonoff_a44000735c
        state: single
action: []
mode: single

alias: Puls Hab 1 Double
description: ''
trigger:
  - platform: event
    event_type: state_changed
    event_data:
      entity_id: sensor.sonoff_a44000735c
condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: sensor.sonoff_a44000735c
        state: double
action: []
mode: single

alias: Puls Hab 1 Long
description: ''
trigger:
  - platform: event
    event_type: state_changed
    event_data:
      entity_id: sensor.sonoff_a44000735c
condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: sensor.sonoff_a44000735c
        state: long
action: []
mode: single












-------------------------------------------


blueprint:
  name: Sonoff SNZB-01 Zigbee Wireless Switch (Cloud)
  description: Automate your Sonoff SNZB-01 Zigbee Wireless Switch (Cloud)
  domain: automation
  input:
    switch:
      name: Sonoff SNZB-01 Zigbee Wireless Switch
      description: Sonoff SNZB-01 Zigbee Wireless Switch to use
      selector:
        entity:
          domain: sensor
    single_press:
      name: Single Press
      description: Action to run on single press
      default: []
      selector:
        action: {}
    double_press:
      name: Double Press
      description: Action to run on double press
      default: []
      selector:
        action: {}
    long_press:
      name: Long Press
      description: Action to run on long press (4 seconds)
      default: []
      selector:
        action: {}
  source_url: https://github.com/frborda/ha-blueprint-Sonoff-SNZB-01-cloud/blob/main/ha_blueprint_Sonoff_SNZB_01_cloud.yaml
mode: restart
max_exceeded: silent
trigger:
- platform: event
  entity_id: !input "sensor"
  attribute: state
state:
- variables:
    command: "{{ trigger.to_state.state }}"
- choose:
  - conditions: 
    - "{{ command == 'single' }}"
    sequence: !input "single"
  - conditions: 
    - "{{ command == 'double' }}"
    sequence: !input "double"
  - conditions: 
    - "{{ command == 'long' }}"
    sequence: !input "long"
