blueprint:
  name: Sonoff SNZB-01 Zigbee Wireless Switch (Cloud)
  description: Automate your Sonoff SNZB-01 Zigbee Wireless Switch (Cloud)
  domain: automation
  input:
    sensor:
      name: Sonoff SNZB-01 Zigbee Wireless Switch
      description: Sonoff SNZB-01 Zigbee Wireless Switch to use
      selector:
        entity:
          domain: sensor
    single:
      name: Single
      description: Action to run on single press
      default: []
      selector:
        action: {}
    double:
      name: Double
      description: Action to run on double press
      default: []
      selector:
        action: {}
    long:
      name: Long
      description: Action to run on long press (4 seconds)
      default: []
      selector:
        action: {}
  source_url: https://github.com/frborda/ha-blueprint-Sonoff-SNZB-01-cloud/blob/main/ha_blueprint_Sonoff_SNZB_01_cloud4.yaml
mode: restart
max_exceeded: silent
trigger:
- platform: event
  event_type: state_changed
state:
- variables:
    command: "{{ trigger.event.data.state }}"
- choose:
  - conditions: 
    - "{{ command == 'single' }}"
    sequence: !input "single"
  - conditions: 
    - "{{ command == 'double' }}"
    sequence: !input "double"
  - conditions: 
    - "{{ command == 'long' }}"
    sequence: !input "long"
